name: Docker Image CI - apcupsd

on:
  push:
    branches: [ master ]
    tags: ['v*']
    paths: [ "apcupsd/**", ".github/workflows/apcupsd.yaml", ".github/workflows/build-and-push.yaml" ]
  pull_request:
    branches: [ master ]
    paths: [ "apcupsd" ]
  workflow_dispatch:

jobs:

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      app: apcupsd
