name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths: [ "avahi" ]
  pull_request:
    branches: [ master ]
    paths: [ "avahi" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP: avahi
      DOCKER_REPO: thisisqasim
      VERSION: latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout Git repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}
