
on:
  workflow_call:
    inputs:
      app:
        description: 'Name of the app'
        required: true
        type: string

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    env:
      APP: ${{ inputs.app }}
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Git repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_REPO }}/${{ env.APP }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,enable=true,prefix=,suffix=,format=short    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        pull: true
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
