name: Docker Image CI - dbus

on:
  push:
    branches: [ "main" ]
    tags: ["v*", "dbus-*"]
    paths: [ "dbus/**", ".github/workflows/dbus.yaml", ".github/workflows/build-and-push.yaml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "dbus" ]
  workflow_dispatch:

jobs:

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      app: dbus
