name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP: elasticsearch
      DOCKER_REPO: thisisqasim

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.8.0'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistro_security-1.9.0.0 opendistro-alerting/opendistro_alerting-1.9.0.0 opendistro-job-scheduler/opendistro-job-scheduler-1.9.0.0 opendistro-index-management/opendistro_index_management-1.9.0.0 opendistro-anomaly-detection/opendistro-anomaly-detection-1.9.0.0 opendistro-sql/opendistro_sql-1.9.0.0
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.9.1'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistro_security-1.11.0.0 opendistro-alerting/opendistro_alerting-1.11.0.1 opendistro-job-scheduler/opendistro-job-scheduler-1.11.0.0 opendistro-index-management/opendistro_index_management-1.11.0.0 opendistro-anomaly-detection/opendistro-anomaly-detection-1.11.0.0 opendistro-sql/opendistro_sql-1.11.0.0
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.10.2'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistro-security-1.13.1.0 opendistro-alerting/opendistro-alerting-1.13.1.0 opendistro-job-scheduler/opendistro-job-scheduler-1.13.0.0 opendistro-index-management/opendistro-index-management-1.13.2.0 opendistro-anomaly-detection/opendistro-anomaly-detection-1.13.0.0 opendistro-sql/opendistro-sql-1.13.2.0 opendistro-reports-scheduler/opendistro-reports-scheduler-1.13.0.0 opendistro-asynchronous-search/opendistro-asynchronous-search-1.13.0.1
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}
