name: Docker Image CI - Kibana

on:
  push:
    branches: [ master ]
    paths: [ "kibana" ]
  pull_request:
    branches: [ master ]
    paths: [ "kibana" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP: kibana
      DOCKER_REPO: thisisqasim

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.8.0'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistro_security_kibana_plugin-1.9.0.0 opendistro-alerting/opendistro-alerting-1.9.0.0 opendistro-index-management/opendistro_index_management_kibana-1.9.0.0 opendistro-anomaly-detection/opendistro-anomaly-detection-kibana-1.9.0.0 opendistro-query-workbench/opendistro-sql-workbench-1.9.0.0
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.9.1'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistro_security_kibana_plugin-1.11.0.0 opendistro-alerting/opendistro-alerting-1.11.0.2 opendistro-index-management/opendistro_index_management_kibana-1.11.0.0 opendistro-anomaly-detection/opendistro-anomaly-detection-kibana-1.11.0.0 opendistro-query-workbench/opendistro-query-workbench-1.11.0.0 opendistro-notebooks/opendistro-notebooks-kibana-1.11.0.0
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}

    - name: Build and push v${{ env.VERSION }}
      uses: docker/build-push-action@v2
      env:
        VERSION: '7.10.2'
      with:
        context: ${{ env.APP }}
        file: ${{ env.APP }}/Dockerfile
        build-args: |
          VERSION=${{ env.VERSION }}
          ODFE_PLUGINS=opendistro-security/opendistroSecurityKibana-1.13.0.1 opendistro-alerting/opendistroAlertingKibana-1.13.0.0 opendistro-index-management/opendistroIndexManagementKibana-1.13.0.1 opendistro-anomaly-detection/opendistroAnomalyDetectionKibana-1.13.0.0 opendistro-query-workbench/opendistroQueryWorkbenchKibana-1.13.0.0 opendistro-notebooks/opendistroNotebooksKibana-1.13.2.0 opendistro-reports/linux/x64/opendistroReportsKibana-1.13.2.0-linux-x64 opendistro-gantt-chart/opendistroGanttChartKibana-1.13.0.0 opendistro-trace-analytics/opendistroTraceAnalyticsKibana-1.13.2.0
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ${{ env.DOCKER_REPO }}/${{ env.APP }}:${{ env.VERSION }}
