name: Docker Image CI - rsync

on:
  push:
    branches: [ "main" ]
    tags: ["v*", "rsync-*"]
    paths: [ "rsync/**", ".github/workflows/rsync.yaml", ".github/workflows/build-and-push.yaml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "rsync" ]
  workflow_dispatch:

jobs:

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      app: rsync
